/**
 * 技能(Skill)目录:25 个真实在售/免费的 AI 技能。
 * 每个 skill 对应 skills/<slug>/SKILL.md(技能说明/方法论),由后端 /api/ai/skill 调 LLM 运行。
 */
export type Skill = {
  slug: string;
  name: string;
  category: "内容创作" | "开发者工具" | "学术研究" | "艺术创作";
  tagline: string;
  price: number;
  inputLabel: string;
  inputPlaceholder: string;
  icon: string;
  from: string;
  to: string;
};

export const SKILL_CATEGORIES = [
  "全部",
  "内容创作",
  "学术研究",
  "艺术创作",
  "开发者工具",
] as const;

export const SKILLS: Skill[] = [
  {
    slug: "xiaohongshu-hit",
    name: "小红书爆款生产线",
    category: "内容创作",
    tagline: "7 公式 + 限流词自检,主题进去、成稿出来",
    price: 59,
    inputLabel: "笔记主题 / 产品",
    inputPlaceholder: "例:敏感肌平价防晒,适合学生党,夏天军训用",
    icon: "image",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "short-video-script",
    name: "短视频脚本工厂",
    category: "内容创作",
    tagline: "3 秒留人、完播带货,照着就能拍",
    price: 69,
    inputLabel: "视频主题 / 产品",
    inputPlaceholder: "例:30 秒种草一款平价蓝牙耳机",
    icon: "video",
    from: "#13a06b",
    to: "#c9a86a",
  },
  {
    slug: "wechat-viral-article",
    name: "公众号爆款长文",
    category: "内容创作",
    tagline: "输入主题,直接出可发布的成稿",
    price: 49,
    inputLabel: "文章主题",
    inputPlaceholder: "例:普通人如何用 AI 做副业,月入 5000",
    icon: "pen",
    from: "#0a5c36",
    to: "#13a06b",
  },
  {
    slug: "content-calendar",
    name: "选题永动机日历",
    category: "内容创作",
    tagline: "一周 7 篇选题一次排完,复制进表格就能用",
    price: 49,
    inputLabel: "账号定位 / 行业",
    inputPlaceholder: "例:做宝妈辅食赛道的小红书号",
    icon: "book",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "ip-persona-builder",
    name: "IP 锚点 · 个人 IP 定位",
    category: "内容创作",
    tagline: "先拆定位,再谈涨粉变现",
    price: 99,
    inputLabel: "你的情况 / 想做什么",
    inputPlaceholder: "例:我是做财务的,想做个副业个人 IP 但不知道定位",
    icon: "users",
    from: "#0e7c5a",
    to: "#c9a86a",
  },
  {
    slug: "commit-pr-cn",
    name: "commit-pr-cn · 中文提交与 PR",
    category: "开发者工具",
    tagline: "把 diff 拆成 30 秒看懂的中文提交和 PR",
    price: 19,
    inputLabel: "git diff / 改动说明",
    inputPlaceholder: "把你的 git diff 粘进来(或描述改了啥)",
    icon: "code",
    from: "#0a5c36",
    to: "#13a06b",
  },
  {
    slug: "code-review-cn",
    name: "中文代码审查官 · 代码挑刺师",
    category: "开发者工具",
    tagline: "四维扫描,专挑英文 review 抓不到的中文坑",
    price: 39,
    inputLabel: "要审查的代码",
    inputPlaceholder: "把要 review 的代码粘进来",
    icon: "sparkles",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "sql-optimizer",
    name: "慢 SQL 急诊室",
    category: "开发者工具",
    tagline: "把慢 SQL 从 10 秒降到 50 毫秒",
    price: 39,
    inputLabel: "慢 SQL 语句",
    inputPlaceholder: "把跑得慢的 SQL 粘进来(附表结构更佳)",
    icon: "layers",
    from: "#13a06b",
    to: "#0e7c5a",
  },
  {
    slug: "prd-to-tech-design",
    name: "方案九段 · 需求转技术设计",
    category: "开发者工具",
    tagline: "10 分钟出评审一次过的技术方案",
    price: 99,
    inputLabel: "需求描述",
    inputPlaceholder: "例:做一个用户积分系统,签到/任务/兑换",
    icon: "target",
    from: "#0e7c5a",
    to: "#c9a86a",
  },
  // ===== 新增 16 个(来自 dd535529 会话,price 0=免费,后续可调) =====
  {
    slug: "academic-research-assistant",
    name: "学术研究脚手架",
    category: "学术研究",
    tagline: "给个题目,出带文献引用的研究框架",
    price: 0,
    inputLabel: "研究主题",
    inputPlaceholder: "例:社交媒体对大学生社交焦虑的影响",
    icon: "book",
    from: "#0a5c36",
    to: "#13a06b",
  },
  {
    slug: "write-academic-paper",
    name: "学术论文写作",
    category: "学术研究",
    tagline: "选题→文献→分章,陪跑整篇论文",
    price: 0,
    inputLabel: "论文题目 / 方向",
    inputPlaceholder: "例:大语言模型在基础教育中的应用研究",
    icon: "book",
    from: "#0a5c36",
    to: "#13a06b",
  },
  {
    slug: "paper-dedup",
    name: "论文降重",
    category: "学术研究",
    tagline: "按段分类→学科策略重写,降重降 AIGC",
    price: 0,
    inputLabel: "要降重的段落",
    inputPlaceholder: "把需要降重的论文段落粘进来",
    icon: "pen",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "painting-coach",
    name: "绘画陪练",
    category: "艺术创作",
    tagline: "构思阶段给你具体可画的创作方案",
    price: 0,
    inputLabel: "想画什么 / 卡在哪",
    inputPlaceholder: "例:想画一张赛博朋克城市,不知道怎么构图",
    icon: "image",
    from: "#13a06b",
    to: "#c9a86a",
  },
  {
    slug: "art-creation",
    name: "艺术创作方案",
    category: "艺术创作",
    tagline: "你定主题与思想,我出完整创作方案",
    price: 0,
    inputLabel: "主题 / 表达意图",
    inputPlaceholder: "例:以「孤独」为主题的一组当代艺术方案",
    icon: "sparkles",
    from: "#13a06b",
    to: "#c9a86a",
  },
  {
    slug: "cold-outreach-engine",
    name: "B2B 冷启动开发信",
    category: "内容创作",
    tagline: "调研+个性化,写高回复率的开发信",
    price: 0,
    inputLabel: "目标客户 / 产品",
    inputPlaceholder: "例:向 SaaS 公司 CTO 推销我们的数据分析工具",
    icon: "pen",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "meeting-notes",
    name: "会议纪要整理",
    category: "内容创作",
    tagline: "录音转写 / 速记 → 正式会议纪要",
    price: 0,
    inputLabel: "会议记录 / 转写",
    inputPlaceholder: "把会议速记或录音转写粘进来",
    icon: "briefcase",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "rewrite",
    name: "改写润色",
    category: "内容创作",
    tagline: "调语气 / 精简 / 去 AI 味 / 换受众",
    price: 0,
    inputLabel: "要改写的文字",
    inputPlaceholder: "把要改写的段落粘进来,说明目标(如:更口语)",
    icon: "pen",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "summarize",
    name: "结构化总结",
    category: "内容创作",
    tagline: "长文 → 结构化总结,不丢关键点",
    price: 0,
    inputLabel: "要总结的长内容",
    inputPlaceholder: "把长文章 / 会议 / 文档粘进来",
    icon: "book",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "translate",
    name: "中英互译",
    category: "内容创作",
    tagline: "保留术语 / 语气 / 格式的高质量翻译",
    price: 0,
    inputLabel: "要翻译的内容",
    inputPlaceholder: "把要翻译的文字粘进来,说明方向(如:中→英)",
    icon: "globe",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "write-blog",
    name: "长文 / 博客写作",
    category: "内容创作",
    tagline: "主题 → 完整长文,有观点有结构",
    price: 0,
    inputLabel: "文章主题",
    inputPlaceholder: "例:为什么每个人都该学一点提示词工程",
    icon: "pen",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "mindmap",
    name: "思维导图",
    category: "开发者工具",
    tagline: "主题 / 文档 → 结构化思维导图",
    price: 0,
    inputLabel: "主题或内容",
    inputPlaceholder: "例:2026 年个人成长规划",
    icon: "layers",
    from: "#13a06b",
    to: "#0e7c5a",
  },
  {
    slug: "name-it",
    name: "起名神器",
    category: "开发者工具",
    tagline: "产品 / 项目 / 公司 / 变量… 一键起名",
    price: 0,
    inputLabel: "给什么起名 + 要求",
    inputPlaceholder: "例:给一个 AI 学习社区起名,要好记有科技感",
    icon: "sparkles",
    from: "#0e7c5a",
    to: "#5bf0b0",
  },
  {
    slug: "prompt-engineering",
    name: "提示词工程",
    category: "开发者工具",
    tagline: "写 / 优化 / 测试系统提示词与模板",
    price: 0,
    inputLabel: "想要什么 prompt",
    inputPlaceholder: "例:帮我写一个让 AI 扮演面试官的系统提示词",
    icon: "code",
    from: "#0a5c36",
    to: "#13a06b",
  },
  {
    slug: "regex",
    name: "正则助手",
    category: "开发者工具",
    tagline: "写 / 解释 / 调试正则,附测试用例",
    price: 0,
    inputLabel: "匹配需求 / 正则",
    inputPlaceholder: "例:匹配中国大陆手机号",
    icon: "code",
    from: "#13a06b",
    to: "#0e7c5a",
  },
  {
    slug: "sql-helper",
    name: "SQL 助手",
    category: "开发者工具",
    tagline: "写 / 优化 / 解释 SQL,附索引建议",
    price: 0,
    inputLabel: "需求 / SQL + 表结构",
    inputPlaceholder: "例:统计每月新增用户数(附 users 表结构)",
    icon: "code",
    from: "#0a5c36",
    to: "#13a06b",
  },
];

export function getSkill(slug: string): Skill | undefined {
  return SKILLS.find((s) => s.slug === slug);
}
